steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/qmk-builder','-f', 'build-environment/Dockerfile', '.' ]
tags: ['build-environment']
images:
- 'gcr.io/$PROJECT_ID/qmk-builder'
