steps:
- name : "gcr.io/qmk-builder-257305/qmk-builder"
  args : [ 'git-submodule']
  id : 'git-submodule'
  waitFor: ['-']
- name : "gcr.io/qmk-builder-257305/qmk-builder"
  args : [ 'planck/rev5:pequenininho', 'idobo:pequenininho', 'keebio/nyquist/rev3:pequenininho', 'planck/rev5:antikythera']
  id : build-firmwares
  waitFor: ['git-submodule']
tags:  ['firmware', 'planck-rev5', 'planck', 'idobo', 'nyquist', 'nyquist-rev3']
artifacts:
    objects:
        location: 'gs://qmk-firmwares'
        paths: ['*.hex']
