steps:
- name : "gcr.io/qmk-builder-257305/qmk-builder"
  args : [ 'git-submodule']
  id : 'git-submodule'
  waitFor: ['-']
- name : "gcr.io/qmk-builder-257305/qmk-builder"
  args : [ 'planck/rev4:pequenininho']
  id : 'planck'
  waitFor: ['git-submodule']
- name : "gcr.io/qmk-builder-257305/qmk-builder"
  args : [ 'idobo:pequenininho']
  waitFor: ['git-submodule']
  id : 'idobo'
- name : "gcr.io/qmk-builder-257305/qmk-builder"
  args : [ 'keebio/nyquist/rev3:pequenininho']
  id : 'nyquist'
  waitFor: ['git-submodule']
artifacts:
    objects:
        location: 'gs://qmk-firmwares'
        paths: ['*.hex']
