steps:
- name : "gcr.io/qmk-builder-257305/qmk-builder"
  args : [ 'git-submodules']
  id : 'git-submodules'
  waitFor: ['-']
- name : "gcr.io/qmk-builder-257305/qmk-builder"
  args : [ 'planck/rev4:pequenininho']
  waitFor: ['git-submodules']
artifacts:
    objects:
        location: 'gs://qmk-firmwares'
        paths: ['*.hex']
